package yhx.com.domain.agent.model.valobj.enums.memory;

public enum MemoryTaskTypeEnumVO {

    TURN_SUMMARY,
    LONG_TERM_MEMORY_EXTRACTION,
    USER_PREFERENCE_EXTRACTION,
    ARTIFACT_SUMMARY,
    ARTIFACT_CHUNK_INDEX,
    SESSION_TASK_SUMMARY,
    CONVERSATION_ROLLUP,
    MEMORY_MERGE,
    MEMORY_RETIRE,
    VECTOR_REINDEX
}
