package cn.bugstack.ai.domain.agent.service.execute.auto.step.factory;

import cn.bugstack.ai.domain.agent.model.entity.AcceptedResultVO;
import cn.bugstack.ai.domain.agent.model.entity.CurrentRoundTaskVO;
import cn.bugstack.ai.domain.agent.model.entity.ExecuteCommandEntity;
import cn.bugstack.ai.domain.agent.model.entity.MasterPlanVO;
import cn.bugstack.ai.domain.agent.model.entity.NextRoundDirectiveVO;
import cn.bugstack.ai.domain.agent.model.entity.OverallStatusVO;
import cn.bugstack.ai.domain.agent.model.entity.PlanStepVO;
import cn.bugstack.ai.domain.agent.model.entity.RoundExecutionSummaryVO;
import cn.bugstack.ai.domain.agent.model.entity.RoundArchiveVO;
import cn.bugstack.ai.domain.agent.model.entity.SessionGoalVO;
import cn.bugstack.ai.domain.agent.model.entity.StepExecutionPlanVO;
import cn.bugstack.ai.domain.agent.model.entity.TaskBoardItemVO;
import cn.bugstack.ai.domain.agent.model.entity.ToolExecutionRecordVO;
import cn.bugstack.ai.domain.agent.model.valobj.AiAgentClientFlowConfigVO;
import cn.bugstack.ai.domain.agent.model.valobj.enums.NextRoundDirectiveTypeEnumVO;
import cn.bugstack.ai.domain.agent.model.valobj.enums.OverallStateEnumVO;
import cn.bugstack.ai.domain.agent.model.valobj.enums.StepStatusEnumVO;
import cn.bugstack.ai.domain.agent.service.execute.auto.step.RootNode;
import cn.bugstack.wrench.design.framework.tree.StrategyHandler;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.stereotype.Service;

import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Factory for the auto-agent execution strategy chain.
 */
@Service
public class DefaultAutoAgentExecuteStrategyFactory {

    private final RootNode executeRootNode;

    public DefaultAutoAgentExecuteStrategyFactory(RootNode executeRootNode) {
        this.executeRootNode = executeRootNode;
    }

    public StrategyHandler<ExecuteCommandEntity, DynamicContext, String> armoryStrategyHandler(){
        return executeRootNode;
    }

    @Data
    @Builder
    @AllArgsConstructor
    @NoArgsConstructor
    public static class DynamicContext {

        private int step = 1;

        private int maxStep = 1;

        private StringBuilder executionHistory;

        private String currentTask;

        boolean isCompleted = false;

        private Map<String, AiAgentClientFlowConfigVO> aiAgentClientFlowConfigVOMap;

        /**
         * Legacy raw input field kept for compatibility with existing nodes.
         */
        private String rawUserGoal;

        /**
         * Sanitized goal used by downstream steps.
         */
        private String sanitizedUserGoal;

        private SessionGoalVO sessionGoal;

        private MasterPlanVO masterPlan;

        private CurrentRoundTaskVO currentRound;

        private OverallStatusVO overallStatus;

        private NextRoundDirectiveVO nextRoundDirective;

        /**
         * Current round plan generated by Node1 and consumed by Node2.
         */
        private StepExecutionPlanVO currentStepPlan;

        /**
         * Plan history by round.
         */
        private Map<Integer, StepExecutionPlanVO> planHistory = new HashMap<>();

        @Builder.Default
        private Map<String, TaskBoardItemVO> taskBoard = new LinkedHashMap<>();

        @Builder.Default
        private Map<Integer, RoundArchiveVO> roundArchive = new LinkedHashMap<>();

        @Builder.Default
        private java.util.List<ToolExecutionRecordVO> toolExecutionLog = new java.util.ArrayList<>();

        @Builder.Default
        private java.util.List<AcceptedResultVO> acceptedResults = new java.util.ArrayList<>();

        private RoundExecutionSummaryVO roundExecutionSummary;

        @Builder.Default
        private Map<String, Object> structuredState = new LinkedHashMap<>();

        private Map<String, Object> dataObjects = new HashMap<>();

        public void initSession(String rawUserInput, int maxRounds) {
            this.step = 1;
            this.maxStep = maxRounds;
            this.executionHistory = new StringBuilder();
            this.currentTask = rawUserInput;
            this.rawUserGoal = rawUserInput;
            this.sanitizedUserGoal = rawUserInput;
            this.isCompleted = false;

            this.sessionGoal = SessionGoalVO.builder()
                    .rawUserInput(rawUserInput)
                    .sanitizedGoal(rawUserInput)
                    .successCriteria("完成所有主步骤并提供可交付结果")
                    .maxRounds(maxRounds)
                    .failurePolicy("PARTIAL_ALLOWED")
                    .build();

            this.masterPlan = MasterPlanVO.builder()
                    .sessionGoal(this.sessionGoal)
                    .planVersion(1)
                    .build();

            PlanStepVO bootstrapStep = PlanStepVO.builder()
                    .stepId("step-1")
                    .title("bootstrap")
                    .goal(rawUserInput)
                    .completionCriteria("产出首轮任务")
                    .status(StepStatusEnumVO.PENDING)
                    .build();
            this.masterPlan.getMainSteps().add(bootstrapStep);

            this.currentRound = CurrentRoundTaskVO.builder()
                    .roundIndex(1)
                    .currentStepId("step-1")
                    .roundTask(rawUserInput)
                    .expectedEvidence("完成首轮任务分配")
                    .toolRequired(false)
                    .status(StepStatusEnumVO.PENDING)
                    .build();

            this.taskBoard.clear();
            this.taskBoard.put("step-1", TaskBoardItemVO.builder()
                    .stepId("step-1")
                    .lastRoundTask(rawUserInput)
                    .attemptCount(0)
                    .status(StepStatusEnumVO.PENDING)
                    .build());

            this.roundArchive.clear();
            this.roundArchive.put(1, RoundArchiveVO.builder().round(1).build());

            this.overallStatus = OverallStatusVO.running();
            this.overallStatus.getRemainingSteps().add("step-1");

            this.nextRoundDirective = NextRoundDirectiveVO.replanSameStep("step-1", "bootstrap");

            this.structuredState.clear();
            this.structuredState.put("sessionGoal", this.sessionGoal);
            this.structuredState.put("masterPlan", this.masterPlan);
            this.structuredState.put("currentRound", this.currentRound);
            this.structuredState.put("overallStatus", this.overallStatus);

            this.toolExecutionLog.clear();
            this.acceptedResults.clear();
            this.roundExecutionSummary = null;
        }

        public <T> void setValue(String key, T value) {
            dataObjects.put(key, value);
        }

        public <T> T getValue(String key) {
            return (T) dataObjects.get(key);
        }
    }

}
